### PR TITLE
[8.4 backport] Restricts the use of the new ByteArray# calling convention.

### PR DESCRIPTION
**Pull request by sorki**
cherry-picked for 8.4 - see #680

### CODE REVIEW

**Comment by ddssff** [comment]
I'm curious about the "backport" designation - is the 8.2 branch of ghcjs considered more advanced than the 8.4 branch?

**Comment by ddssff** [comment]
I just built all our stuff with this patch applied, no (new) problems.

**Comment by ddssff** [comment]
Actually, maybe I am...

**Comment by sorki** [comment]
Oh, I didn't even notice the parent pull request targets master. Let's call this forwardport :]

**Comment by luite** [comment]
hm, this request targets `ghc-8.4`, right?

I've merged a calling convention fix in that branch. Is this still needed?

**Comment by luite** [comment]
I think the existing fix works, but it took me rather too long to push it.
I'm sorry for not including your work, I appreciated the PR!

**Pull request closed without merging**
