### PR TITLE
Add <meta> tag

### PR DESCRIPTION
**Pull request by dmjio**
Receive strange hieroglyphs w/ certain css styles without this

### CODE REVIEW

**Comment by luite** [comment]
Do you also get this with the standard index.html?

**Comment by luite** [comment]
(for normal apps I mean, I was wondering if it should also be added there, rather than just for GHCJSi)

**Comment by dmjio** [comment]
@luite, yes it appears this occurs for both normal apps and on the the socket.io produced index.html as well. 

screen shot 2016-07-02 at 10 14 06 am

I can append another commit updating the index.html as well.

**Comment by dmjio** [comment]
@luite should be on both now

**Comment by luite** [comment]
Better to fix them both at once then. Thanks for the fix. I'll squash the commits into a single one though.

**Comment by dmjio** [comment]
@luite ok, sounds good.

**Comment by luite** [comment]
Thanks, commited (PR didn't close automatically due to the rebase for squashing the commits into one)

**Pull request closed without merging**
