### PR TITLE
Drop 7.8 compatibility and -Wall clean

### PR DESCRIPTION
**Pull request by meiersi**
First steps towards #438 . What remains to be done is
- get rid of unused binds, missing pattern match warnings: @luite could you do that?
- get rid of support for template-haskell < 2.10
- make a test run
- compile on windows and make a test run there too

### CODE REVIEW

**Comment by Ericson2314** [comment]
Can this be merged?

**Comment by cartazio** [comment]
is this PR out of date or does it still make sense?

**Comment by luite** [comment]
sorry the inactivity, this broke my work tree so I held off merging it far too long. In the meantime I've gradually removed obsolete code and fixed some warnings

**Comment by meiersi** [comment]
No problem. Thx for all the great work!
Luite Stegeman <notifications@github.com> schrieb am So. 6. Mai 2018 um
13:43:

**Pull request closed without merging**
