### PR TITLE
Tweak the lens dependency again.

### PR DESCRIPTION
**Pull request by mdorman**

### CODE REVIEW

**Comment by spl** [comment]
Just pinging on this. Does the update to lens cause a problem? If not, it would be nice to get this change in. Thanks!

**Comment by luite** [comment]
Apologies. I'm more focused on the `improved-base` branch these days.

**Comment by mdorman** [comment]
No apology necessary---we look forward to when improved-base is ready. :)

**Comment by spl** [comment]
@luite Thanks! As a GHCJS neophyte, how should I keep informed about updates and new developments?

**Pull request merged**
