### PR TITLE
Fix handling of cmdline args for --install-executable #383

### PR DESCRIPTION
**Pull request by mgsloan**

### CODE REVIEW

**Comment by luite** [comment]
thanks, I must've broken this when integrating the additional ghcjs command line options into the main program.

**Comment by kfigiela** [comment]
It seems that it breaks building of some packages with cabal: 
```Resolving dependencies...
Configuring pretty-show-1.6.8.2...
Building pretty-show-1.6.8.2...
Preprocessing library pretty-show-1.6.8.2...
[1 of 6] Compiling Paths_pretty_show ( dist/dist-sandbox-b2964a4d/build/autogen/Paths_pretty_show.hs, dist/dist-sandbox-b2964a4d/build/Paths_pretty_show.js_o )
[2 of 6] Compiling Text.Show.Value  ( Text/Show/Value.hs, dist/dist-sandbox-b2964a4d/build/Text/Show/Value.js_o )
[3 of 6] Compiling Text.Show.PrettyVal ( Text/Show/PrettyVal.hs, dist/dist-sandbox-b2964a4d/build/Text/Show/PrettyVal.js_o )
[4 of 6] Compiling Text.Show.Html   ( Text/Show/Html.hs, dist/dist-sandbox-b2964a4d/build/Text/Show/Html.js_o )

Text/Show/Html.hs:106:1: Warning: Defined but not used: ‘tallTuple’
[5 of 6] Compiling Text.Show.Parser ( dist/dist-sandbox-b2964a4d/build/Text/Show/Parser.hs, dist/dist-sandbox-b2964a4d/build/Text/Show/Parser.js_o )
[6 of 6] Compiling Text.Show.Pretty ( Text/Show/Pretty.hs, dist/dist-sandbox-b2964a4d/build/Text/Show/Pretty.js_o )
In-place registering pretty-show-1.6.8.2...
Preprocessing executable 'ppsh' for pretty-show-1.6.8.2...
[1 of 1] Compiling Main             ( bin/ppsh.hs, dist/dist-sandbox-b2964a4d/build/ppsh/ppsh-tmp/Main.js_o )
Linking dist/dist-sandbox-b2964a4d/build/ppsh/ppsh.jsexe (Main)
Creating package registration file:
/var/folders/pc/79dcz63d0zl123lf9zjfj5xc0000gn/T/pkgConf-pretty-show-1.6.8178448449274243042.2
Installing library in
/Users/kamilfigiela/NewByteOrder/development/nodelab-gui/.cabal-sandbox/lib/x86_64-osx-ghcjs-0.1.0-ghc7_10_2/pretty-show-1.6.8.2-KV2Fd7Oxe2P9WS3biXDypo
Installing executable(s) in
/Users/kamilfigiela/NewByteOrder/development/nodelab-gui/.cabal-sandbox/bin
Usage: ghcjs --install-executable <from> -o <to>
Failed to install pretty-show-1.6.8.2
cabal: Error: some packages failed to install:
nodelab-0.1.0.0 depends on pretty-show-1.6.8.2 which failed to install.
pretty-show-1.6.8.2 failed during the final install step. The exception was:
ExitFailure 1```

**Comment by mgsloan** [comment]
@kfigiela Very curious, that's the behavior I was getting out of `runhaskell Setup.hs install`, before this change.

**Comment by kfigiela** [comment]
Here's log from `cabal install --ghcjs --verbose` for `ghcjs-dom-hello` https://gist.github.com/kfigiela/587d14e41ee195b7b441.

**Pull request merged**
