### PR TITLE
add missing primops for resizeMutableByteArray, shrinkByteArray, and getSizeofMutableByteArray

### PR DESCRIPTION
**Pull request by andrewthad**
Someone should look this over since I've never committed anything to GHCJS before. Resolves https://github.com/ghcjs/ghcjs/issues/686

### CODE REVIEW

**Comment by andrewthad** [comment]
I'm going to try this out in our development environment. I'm mostly concerned about the implementation for `shrinkMutableByteArray#`. I think I've got the right way to do it in-place.

**Comment by andrewthad** [comment]
Also worth mentioning that I added this to the 8.4 branch. Technically, these primops have been available since GHC 8.2 though.

**Comment by andrewthad** [comment]
Has anyone looked at this?

**Comment by hvr** [comment]
>  Technically, these primops have been available since GHC 8.2 though.

*Actually*... I implemented `shrinkMutableByteArray#` and `resizeMutableByteArray#` back then for GHC 7.10 in order to support the next-gen integer-gmp rewrite ; it's only `getSizeofMutableByteArray#` that got added later in GHC 8.0

**Comment by luite** [comment]
thanks I've merged these in the `ghc-8.4` branch.

I moved the implementation to `mem.js`, since I don't think having it inline will make much of a difference for performance.

**Pull request closed without merging**
