### PR TITLE
Add link to Stack+GHCJS instructions in README

### PR DESCRIPTION
**Pull request by eallik**
Not sure if the wording's right, but I reckoned something like this ought to be in the README.

### CODE REVIEW

**Comment by bergey** [comment]
I really like using stack for GHCJS projects, and linking to the docs seems like a great idea.  I think the wording could be more clear for people not already using stack.  Maybe something like:

```
Stack can be used to build projects with GHCJS, including dependencies from Hackage or from git.  
Stack can also automatically install GHCJS from a specific sdist tarball.
```

Of course it's great if @luite wants to merge this immediately, and I can bikeshed in my own PR =)

**Comment by 3noch** [comment]
I'm not sure how @luite feels about people using his nightly sdists, but I have a script I use for myself: https://gist.github.com/3noch/4696feff5c602e126681

**Comment by eallik** [comment]
Updated wording according to @bergey's suggestion.

**Comment by mgsloan** [comment]
I have written some text for this - 6b42b45 and b7c28ca2d7eab7aaa3ef324643545bba4c10e395

**Pull request closed without merging**
