### PR TITLE
Bump aeson, syb, and text-binary bounds

### PR DESCRIPTION
**Pull request by cstrahan**
This bumps the bounds for aeson, syb, and text-binary. This should be rolled out with https://github.com/ghcjs/ghcjs-boot/pull/27.

I'm running a build right now; I'll report back with the results.

### CODE REVIEW

**Comment by yiding** [comment]
I also had to do this (building with nix where the system's version of these packages moved on) and it compiled fine. The CI failure seems to be directly unrelated.

**Comment by ddssff** [comment]
Attoparsec can also be bumped to < 0.14

**Comment by geraldus** [comment]
@ddssff looks like it's already `< 0.14`.

**Comment by dmjio** [comment]
+1

**Pull request merged**
