### PR TITLE
Implement a web-frontend

### PR DESCRIPTION
**Pull request by sumitsahrawat**

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
Sorry, didn't mean to merge here.

**Comment by luite** [comment]
Still I'm quite interested in this kind of application and would like to help out figuring out the `GHCJSi` design changes we'd need to make this as easy and good as possible. Do you have some documents that describe what you need, or is there perhaps some kind weekly progress meeting for you project that I could attend?

**Comment by sumitsahrawat** [comment]
@luite Thanks for offering to help :+1: I've created a repository [sumitsahrawat/IHaskellJS](https://github.com/sumitsahrawat/IHaskellJS), and a corresponding gitter channel which we can use to chat. I've added you and @gibiansky to the channel.

I've just come to somewhat understand the source code, and have a rough idea of what I want to do. I'll prepare a specification, and put it in the repository.

**Comment by agocorona** [comment]
Could you implement the web front-end independently from IHaskell?  I would like a notebook but for using my own library.

**Comment by sumitsahrawat** [comment]
The final goal is to create a jupyter kernel for GHCJS. I'm trying to implement a basic web front-end to understand what changes need to be made to GHCJS itself.

The kernel will be independent from IHaskell, and you will be able to use it to work with any library, just like IHaskell.

**Pull request closed without merging**
