### PR TITLE
Provide CPP stubs for foreign imports

### PR DESCRIPTION
**Pull request by spl**
This is useful for type-checking code using `ghcjs-prim` in GHCi. The stubs are errors, so the stubbed functions will throw exceptions (explaining why they exist) when evaluated.

I would find this very valuable for daily development, since it's much faster to type-check code in GHC than GHCJS. I've been maintaining stubs in my own code for a while, but it's a pain. This change means that the stubs will always have the same types as the `foreign import`s.

This PR is targeted at the `master` branch. If you're happy with it, I can create a PR to update `ghc-8.0` and another PR to target the `foreign import`s in `ghcjs-base`.

### CODE REVIEW

**Comment by spl** [comment]
@ryantrinkle on IRC:

> well, i might be a bit concerned about accidentally using something in a GHC app without realizing it's not available
> maybe it would make sense to make it configurable?

**Comment by spl** [comment]
@ryantrinkle: I'm not sure what you might accidentally do in a GHC app. Could you give an example?

Without this change, `ghcjs-prim` doesn't compile with GHC. With this change, all stubbed `foreign import`s throw exceptions, and those exceptions explain themselves (unless somebody has a suggestion for an improvement that would make them more self-evident).

I feel a flag is not necessary and adds a burden to those who want to use the package in GHCi. (And, if we also change `ghcjs-base`, it will presumably need a flag, too, increasing the burden.)

I'd rather keep things simple and not require a flag. As soon as you try to do anything in GHC with the package, you'd see the exception.

**Comment by hamishmack** [comment]
Long term the best fix would be to make GHC output the code we need to implement JS FFI calls.

What do you need from `ghcjs-prim` that is not exposed by `ghcjs-dom`?  It might be a better idea to expose the `ghcjs-prim` functions in `ghcjs-dom-jsffi` and include `jsaddle` based implementations for GHC to `ghcjs-dom-jsaddle`.  That way you can type check and run your code with GHC and GHCi.

**Comment by spl** [comment]
@hamishmack:

> Long term the best fix would be to make GHC output the code we need to implement JS FFI calls.

Do you mean that GHC should be modified to support `foreign import javascript`? That would basically involve merging GHCJS into GHC. That's a nice goal, but I'm not holding my breath.

> What do you need from `ghcjs-prim` that is not exposed by `ghcjs-dom`?

Actually, what I needed is mostly from `ghcjs-base` but `ghcjs-base` depends on `ghcjs-prim`, so that's where I've started.

See the code at the end for some of the stubs I had with an old version of GHCJS. Attempting to upgrade to a new GHCJS is what inspired this PR.

> It might be a better idea to expose the `ghcjs-prim` functions in `ghcjs-dom-jsffi` and include `jsaddle` based implementations for GHC to `ghcjs-dom-jsaddle`. That way you can type check and run your code with GHC and GHCi.

I'm all for being able to run and type-check GHCJS-based code in GHC. It would certainly be nice to have a complete compatibility layer for `ghcjs-prim`/`ghcjs-base`, but I have not found one.

I'm not familiar with `jsaddle`. I glanced at it once, but the description “an EDSL for calling JavaScript code using the JavaScriptCore engine and low level Haskell bindings in the webkit-javascriptcore” didn't look like anything I needed.

If you already have some existing compatibility layer, would you mind pointing me to it?

```haskell
type JSRef a = ForeignPtr a
data JSFun a

class ToJSRef a where
  toJSRef :: a -> IO (JSRef a)
instance ToJSRef Bool
instance ToJSRef Char
instance ToJSRef Int
instance ToJSRef Double
instance ToJSRef Float
instance ToJSRef a => ToJSRef [a]
instance ToJSRef a => ToJSRef (Maybe a)
instance (ToJSRef a, ToJSRef b) => ToJSRef (a, b)
instance ToJSRef DOMWindow

castRef :: JSRef a -> JSRef b
castRef = undefined

data JSString_
type JSString = JSRef JSString_

instance IsString JSString

class ToJSString a where
  toJSString :: a -> JSString
instance ToJSString JSString
instance ToJSString String

class FromJSString a where
  fromJSString :: JSString -> a
instance FromJSString String
instance FromJSString JSString

newObj :: IO (JSRef a)
newObj = undefined

setProp :: JSString -> JSRef a -> JSRef b -> IO ()
setProp = undefined

data ForeignRetention = NeverRetain | AlwaysRetain | DomRetain (forall a. JSRef a)

syncCallback :: ForeignRetention -> Bool -> IO a -> IO (JSFun (IO a))
syncCallback = undefined

syncCallback1 :: ForeignRetention -> Bool -> (JSRef a -> IO b) -> IO (JSFun (JSRef a -> IO b))
syncCallback1 = undefined

asyncCallback1 :: ForeignRetention -> (JSRef a -> IO b) -> IO (JSFun (JSRef a -> IO b))
asyncCallback1 = undefined

release :: JSFun a -> IO ()
release = undefined

jsNull :: JSRef a
jsNull = undefined
```

**Comment by hamishmack** [comment]
> I'm not familiar with jsaddle. I glanced at it once, but the description “an EDSL for calling JavaScript code using the JavaScriptCore engine and low level Haskell bindings in the webkit-javascriptcore” didn't look like anything I needed.

I have updated the [readme.md](https://github.com/ghcjs/jsaddle#jsaddle).  I hope to release a new version of `jsaddle` and `ghcjs-dom` based on what is in github very soon.

> If you already have some existing compatibility layer, would you mind pointing me to it?

It's not all in one place.  The module [Language.Javascript.JSaddle.Types](
https://github.com/ghcjs/jsaddle/blob/master/src/Language/Javascript/JSaddle/Types.hs#L17) for instance exports some `ghcjs-base` types when compiled with GHCJS.  It implements them itself when compiled with GHC.

**Comment by spl** [comment]
@hamishmack: Thanks for the pointer to the `README.md` (which I seem to have missed) and the update. I now have a better idea what `jsaddle` is.

It seems like `jsaddle`, perhaps via `ghcjs-dom`, would be the way to go to build an app to work both in the browser with GHCJS and from a server run with GHC.

I see a couple of options for future work:

1. Develop a GHCJS/GHC compatibility package for `ghcjs-prim` and `ghcjs-base` that would cover more of the APIs than `jsaddle` currently does. This has the downsides of (a) requiring changes to be synced to those of `ghcjs-prim` and `ghcjs-base` and (b) possibly not being in line with your goals for `jsaddle`.

2. Adapt `ghcjs-prim` and `ghcjs-base` (or perhaps just `ghcjs-base` alone but including certain things exported by `ghcjs-prim`) to work for both GHCJS and GHC. That would alleviate the problem of syncing changes.

I'm happy to collaborate on either of those. The second option would be my choice, if I had to choose.

Right now, I'm mainly interested in being able to quickly type-check code intended for the browser with GHCJS. It really helps with development to avoid waiting on GHCJS to build. So, in the short term, I think having the `foreign import`s stubbed out would be extremely useful and also somewhat orthogonal to such goals as the above. (It's orthogonal in the sense that code on GHC might go from not compiling to only type-checking to possibly running; thus, nothing is actually lost.)

**Comment by hamishmack** [comment]
> Thanks for the pointer to the README.md (which I seem to have missed)

Oh you did not miss it, I wrote it yesterday.  I have just finished working on `jsaddle-0.5` and before yesterday that readme was just one line (and that was out of date).

> Develop a GHCJS/GHC compatibility package for ghcjs-prim and ghcjs-base that would cover more of the APIs than jsaddle currently does.

Why not just add them to `jsaddle-0.6`?  `jsaddle` started out looking a lot more like `webkitgtk-javascriptcore` because that was used for the native implementation.  Over time I have tried to make it use more and more of `ghcjs-base` directly.

> Adapt ghcjs-prim and ghcjs-base (or perhaps just ghcjs-base alone but including certain things exported by ghcjs-prim) to work for both GHCJS and GHC. That would alleviate the problem of syncing changes.

The GHC types in `ghcjs-prim` are designed to work with the (currently dormant) native code gen of GHCJS.  For instance JSVal is a ForeignPtr and in `jsaddle` in it is a Haskell type.

There is a plan to make the native code gen work one day.  We will be able to borrow much of what we learn making `jsaddle` (and perhaps some of the code) when we do.

> I think having the foreign imports stubbed out would be extremely useful and also somewhat orthogonal to such goals as the above.

I fear people might be less likely to try out `jsaddle` and help with its development if we add them.

I also worry the stubs might slip into someones production code by mistake.  In an application using `jsaddle` that also used `ghcjs-prim` it would be easy to use a stub function by mistake (thinking it had already been implemented in `jsaddle`).

**Comment by spl** [comment]
To appease the concerns about accidentally using `ghcjs-prim` with GHC and encountering errors, I've changed the PR to put the stubs behind a flag, meaning you must explicitly declare that you want `-fforeign-import-stubs` in order to get them.

@hamishmack:

> Why not just add them to jsaddle-0.6?

I would prefer to have a minimal API to keep the complexity of the code reduced and a minimal code base to keep the compiled output size down. (This is why I think having `ghcjs-prim`/`ghcjs-base` work for both GHCJS and GHC is the preferred option.) The organization and apparent goal of `jsaddle` is quite different from `ghcjs-prim`/`ghcjs-base`, so it's not clear looking in the two directions how one would use only the features of `ghcjs-prim`/`ghcjs-base` with `jsaddle` as the middleman.

> There is a plan to make the native code gen work one day. We will be able to borrow much of what we learn making jsaddle (and perhaps some of the code) when we do.

I think that's a good plan. However, it doesn't resolve the current need to be able to load `ghcjs-prim`/`ghcjs-base` into GHCi.

> I fear people might be less likely to try out jsaddle and help with its development if we add them.

I don't understand this concern. You're saying that `foreign import` stubs – which only provide a type and do not add any functionality – would convince people to not try out a library that provides functionality for two platforms? That statement makes it sound like you think the _only_ way to support both GHC and GHCJS would be to use and improve `jsaddle`, because any competition (even just stubs) would make people less likely to do so. (You may not think that, but I think it is a reasonable interpretation for that statement.) I'm afraid I don't agree with that.

**Comment by hamishmack** [comment]
> To appease the concerns about accidentally using ghcjs-prim with GHC and encountering errors, I've changed the PR to put the stubs behind a flag, meaning you must explicitly declare that you want -fforeign-import-stubs in order to get them.

It might be safer as a separate package (since you can't specify flag requirements in `build-depends:`).

> The organization and apparent goal of jsaddle is quite different from ghcjs-prim/ghcjs-base, so it's not clear looking in the two directions how one would use only the features of ghcjs-prim/ghcjs-base with jsaddle as the middleman.

The goal would be to get everything you need into `ghcjs-dom`.  The `ghcjs-dom` layer is trying to provide the optimal functions for both GHCJS and GHC.   We can export `ghcjs-prim` and `ghcjs-base` types and functions from `ghcjs-dom` when using GHCJS (and we already do), but before we export them we need an implementation for GHC and that is where `jsaddle` comes in.  You would not have to use `jsaddle` at all in your GHCJS build (just `ghcjs-dom`).

> I would prefer to have a minimal API to keep the complexity of the code reduced and a minimal code base to keep the compiled output size down.

When you say "output size" do you mean GHC or GHCJS output size?  GHC output size should not matter too much if you are only type checking and GHCJS should exclude unused functions from the output.

> > I fear people might be less likely to try out jsaddle and help with its development if we add them.

> I don't understand this concern. You're saying that `foreign import` stubs – which only provide a type and do not add any functionality – would convince people to not try out a library that provides functionality for two platforms? That statement makes it sound like you think the _only_ way to support both GHC and GHCJS would be to use and improve `jsaddle`, because any competition (even just stubs) would make people less likely to do so. (You may not think that, but I think it is a reasonable interpretation for that statement.) I'm afraid I don't agree with that.

It is not that I think `ghcjs-dom` and `jsaddle` are the only way to go, but it does seem to me like we would be giving the prime location to the stubs.  I would be a lot less worried if the stubs were not in `ghcjs-prim` itself.  Then people could choose `ghcjs-dom`, `ghcjs-prim-ghc-stubs` or something else.  I would still be unhappy if people did not give `ghcjs-dom` a go, but I understand it may not be to everyones liking.

**Comment by spl** [comment]
> It might be safer as a separate package (since you can't specify flag requirements in build-depends:).

Speaking of safety, you reminded me of the `manual:` option for flags. I've added that so that `cabal` won't try to use a different value for the flag.

Otherwise, I'm not sure what you mean by “safer” here. If the flag is there and false by default, it won't be enabled; thus, it is not possible to introduce errors. I don't see anything unsafe about it.

Anyway, I agree that it is rather inconvenient to have a flag instead of a default stub. (And, as I said earlier, I would prefer not having a flag.) But you can enable the flag using `stack` by putting it in a `stack.yaml`:

```
flags:
  ghcjs-prim:
    foreign-import-stubs: true
```

Not everybody uses `stack`, of course. Another way to enable the stubs would be to clone the repository, change the default for `foreign-import-stubs` to `True`, and vendor it in an application repository. So, the fact is that the flag at least makes this possible.

I don't currently plan on creating separate packages just to have stubs. I expect that `ghcjs-prim`+`ghcjs-base` will be changing. It's easier to maintain just the interface that I use from those libraries. On the other hand, I thought the `FOREIGN_IMPORT` macro was quite useful, easy to use, and worth contributing to the community to allow everybody the joy of type-checking their GHCJS code in GHC.

> When you say "output size" do you mean GHC or GHCJS output size?

GHCJS.

> GHCJS should exclude unused functions from the output.

Yes, ideally, it should. I should also add the concern of compile time, which increases with every package (and possibly with every unused function).

> It is not that I think ghcjs-dom and jsaddle are the only way to go, but it does seem to me like we would be giving the prime location to the stubs. I would be a lot less worried if the stubs were not in ghcjs-prim itself. Then people could choose ghcjs-dom, ghcjs-prim-ghc-stubs or something else. I would still be unhappy if people did not give ghcjs-dom a go, but I understand it may not be to everyones liking.

I guess I fail to fully comprehend this argument.

I don't see `ghcjs-dom` as being quite so relevant to the discussion. Sure, it would be great to write an app using `ghcjs-dom` that works for both GHC and GHCJS. But there are some primitive things that I would not expect `ghcjs-dom` to cover that exist in `ghcjs-prim`+`ghcjs-base`. And there are some people, I might expect, who would use `ghcjs-prim`+`ghcjs-base` without using `ghcjs-dom`.

It would be even better, I think, if `ghcjs-prim`+`ghcjs-base` worked on both GHC and GHCJS. There would be no need for stubs. But this is not currently the case.

Perhaps I see the impact of this CPP macro differently from others:

* It's impact on the library code itself is quite small. It simply makes it possible to write a single `foreign import javascript` declaration that works in GHCJS and type-checks in GHC. That's all it does, and the maintaining the code is no more difficult than if there were only `foreign import javascript` declarations.
* It's impact on the usefulness of the library is tremendous for some people. Nobody has to maintain a duplicate interface just for type-checking in GHC.

The existence of GHC stubs, as far as I can see, neither precludes nor discourages any development on cross-platform libraries. Since the stubs provide no functionality, there is nothing you can do with them in GHC _except_ type-check.

If there is an argument that (a) people should be forced or encouraged to use a functionality-providing cross-platform library instead of stubs or (b) stubs should be on a level playing ground with functionality-providing cross-platform libraries, that argument doesn't seem to hold much water to me. First, functionality-providing cross-platform libraries serve a very different purpose from stubs, namely providing functionality. Second, asking somebody to use a functionality-providing cross-platform library when they simply want to type-check single-platform code seems like unnecessary coercion and overkill for the problem. Third, I believe that stubs not maintained with the stubbed code tend to fall out of sync. I've seen enough evidence of this that I feel confident it would be the case.

**Comment by hamishmack** [comment]
>> GHCJS should exclude unused functions from the output.

> Yes, ideally, it should. I should also add the concern of compile time, which increases with every package (and possibly with every unused function).

What if we split `ghcjs-dom` into:

* `ghcjs-dom-prim` (git branch of `ghcjs-prim` for GHC)

* `ghcjs-dom-base` (git branch of `ghcjs-base` for GHC)

* `ghcjs-dom` (the rest)

When compiled with GHCJS `ghcjs-dom-prim` and `ghcjs-dom-base` would be empty.  You won't need `ghcjs-dom` at all.

We can merge changes in from the master branch to keep up to date.

We can merge your stubs as per the the pull request (including the flag to enable them).  Then we can start work on replacing the stubs with working code.

Eventually if it goes well enough and everyone agrees we could merge back into master.

**Comment by hamishmack** [comment]
Also `ghcjs-dom-prim` and `ghcjs-dom-base` would be uploaded to Hackage. So anyone wanting the stubs would just need to add the package to `build-deps:` and set the flag.

**Comment by spl** [comment]
@hamishmack: I'm intrigued, but I'm not sure if I understand you correctly. Let me say it another way to see if you agree:

1. We create two new packages, `ghcjs-dom-prim` and `ghcjs-dom-base`.
2. For `impl(ghcjs)`, each new package would simply re-export the modules of the respective `ghcjs-prim` or `ghcjs-base`.
3. For other implementations (basically, GHC), each new package would export the same modules as `ghcjs-prim` or `ghcjs-base` and provide a working implementation.

Is that the gist of it?

**Comment by hamishmack** [comment]
> Is that the gist of it?

Yes.

In addition I will look into splitting up the rest of ghcjs-dom in line with directory of the IDL file (see [webkit.idl](https://github.com/ghcjs/ghcjs-dom/blob/master/webkit.idl#L38) in ghcjs-dom for a list of the IDL files we use).  For each directory we will need a ghcjs-dom-X-types package to contain just the types (since they might be needed for the other packages).  That would give us something like:

```
ghcjs-dom-airplay
ghcjs-dom-battery
ghcjs-dom-encryptedmedia
ghcjs-dom-gamepad
ghcjs-dom-geolocation
ghcjs-dom-indexeddb
ghcjs-dom-indieui
ghcjs-dom-mediacontrols
ghcjs-dom-mediasession
ghcjs-dom-mediasource
ghcjs-dom-mediastream
ghcjs-dom-navigatorcontentutils
ghcjs-dom-notifications
ghcjs-dom-plugins
ghcjs-dom-proximity
ghcjs-dom-quota
ghcjs-dom-speech
ghcjs-dom-streams
ghcjs-dom-vibration
ghcjs-dom-webaudio
ghcjs-dom-webdatabase
ghcjs-dom-websockets
ghcjs-dom-crypto
ghcjs-dom-css
ghcjs-dom-dom
ghcjs-dom-fileapi
ghcjs-dom-html
ghcjs-dom-canvas
ghcjs-dom-track
ghcjs-dom-inspector
ghcjs-dom-appcache
ghcjs-dom-page
ghcjs-dom-plugins
ghcjs-dom-storage
ghcjs-dom-svg
ghcjs-dom-testing
ghcjs-dom-workers
ghcjs-dom-xml
```

Plus a -types package for each.

**Comment by spl** [comment]
@hamishmack: Okay, I get the `ghcjs-prim` and `ghcjs-base` wrappers.

I think you could simplify to having just one package, e.g. `ghcjs-dom-base`, that covers everything from `ghcjs-prim` and `ghcjs-base`. I don't think there's a need to create a `ghcjs-dom-prim` package because `ghcjs-prim` isn't much without `ghcjs-base`.

As for splitting up `ghcjs-dom`, why do you think that is necessary? It seems to make the package selection unwieldy.

**Comment by hamishmack** [comment]
> As for splitting up ghcjs-dom, why do you think that is necessary? It seems to make the package selection unwieldy.

We would still have have `ghcjs-dom` and it would just re-export everything.  But lets say you were writing wrappers for a JS library that included functions that take a JavaScript `HTMLElement` as a parameter. It kind of sucks that you would have to depend on the whole of `ghcjs-dom` to get compatible types.  Instead you could just depend on `ghcjs-dom-html-types` to get `HTMLElement` and `IsHTMLElement`.

**Comment by spl** [comment]
@hamishmack: I understand the supposed rationale, but is it an actual problem? What does one really lose by depending on all of `ghcjs-dom`? Also, consider that if you're writing JavaScript, you wouldn't select the DOM piecemeal. It's all there, ready for you to use whatever you need when you need it.

I think the downsides of splitting are:

1. It takes more work to find what you need because you have to figure out what package it's in.
2. It creates significantly more work for you, as maintainer, to make changes and publish all of the packages.

**Comment by spl** [comment]
Also, don't forget the compile time. Now you need to compile something like 70+ packages instead of a few.

**Comment by hamishmack** [comment]
> It takes more work to find what you need because you have to figure out what package it's in.

True.  It might help if we wait until cabal reexported modules are well supported in tools like haddock and hoogle.

> It creates significantly more work for you, as maintainer, to make changes and publish all of the packages.

It's enough that I would have to script it.

Alternatively we could go with the approach that `haskell-gi` uses and generate the code on the fly.  So the packages would be stubs and we would have the `domconv` code and IDL files in another package say `ghcjs-dom-gen` and that would be the only one that really ever needed to change.  All the other packages would only contain a .cabal file indicating which of the IDL files to generate code for (like this [gi-gtk.cabal](http://hackage.haskell.org/package/gi-gtk-3.0.6/gi-gtk.cabal) cabal file tells haskell-gi which GObject introspection library to generate code for).  I'm not keen on doing that until [this](https://github.com/commercialhaskell/stack/issues/2094) is fixed though.

> Also, don't forget the compile time. Now you need to compile something like 70+ packages instead of a few.

Actually compile time might go down.  Currently `ghcjs-dom` (or `jsaddle-dom` for GHC) contains one very big and slow `Types` module and 530 other modules that get compiled one at a time.  Unless you are lucky your other cores sit idle while this happens.  Splitting it out will give cabal-install or stack a much better chance to spread the load over multiple cores.

**Comment by spl** [comment]
I wasn't aware of the `reexported-modules` field in `.cabal` files. Interesting.

I'm still not convinced it's a good idea to split the packages. I think the gain does not overcome the loss, both for the developer/maintainer and for the user. But, of course, it's your choice.

**Comment by spl** [comment]
For a recent example of where the `FOREIGN_IMPORT` change to `ghcjs-prim` and `ghcjs-base` (preferably without the flag) would help, see reflex-frp/reflex-dom-semui#3. The entire [`GHCJS.Compat` module](https://github.com/reflex-frp/reflex-dom-semui/blob/a6727745fc81e462cac4cdbaf05b15fce13406f4/src-ghc/GHCJS/Compat.hs) would not be necessary.

Nonetheless, it seems that we might have a new `master` soon (#526), so it would probably be best to avoid merging this now. I may get around to making another PR against the new `master` at some point.

**Comment by hamishmack** [comment]
See the current [reflex-dom-semui](https://github.com/reflex-frp/reflex-dom-semui) for an example of how to use `jsaddle` and `ghcjs-dom` to get your `ghcjs` code to compile and run on `ghc`.  Keep in mind that if you don't care if it runs you can leave all your leave the `ghc` versions of your function `undefined` in the hope someone else will implement them.

**Pull request closed without merging**
