### PR TITLE
Support for windows 

### PR DESCRIPTION
**Pull request by jneira**
Hi, i've been working lately trying to add support for windows.
I've got to run `ghcjs-boot` up to build directory (or unix, more on that later) package in  stage-1b.

The last wall is work around the fact `ghcjs` defines it own operating system for cabal (`os(ghcjs)`) and cpp(`ghcjs_HOST_OS`) replacing `os(windows)` and `mingw32_HOST_OS`. 

So `ghcjs-boot` is passing `win32` package to cabal install but the cabal conditionals ask for `unix` one.

As in commit fd10c70 the error so far is:
```console
cabal.exe: Could not resolve dependencies:
[__0] trying: directory-1.3.3.0 (user goal)
[__1] unknown package: unix (dependency of directory)
[__1] fail (backjumping, conflict set: directory, unix)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: directory (2), unix (1)
```

AFAIU the alternatives could be:
- Try to reinstate `os(windows)` and `mingw32_HOST_OS` via cabal flag `-fghcjs-windows`
  - Suggested in https://github.com/ghcjs/ghcjs/issues/548#issuecomment-266212942
  - In cabal files:
```cabal
flag ghcjs-windows
  default False

if flag(ghcjs-windows)
  cpp-option: -Dmingw32_HOST_OS
```
.. and replace all `if os(windows)` with `if os(windows) || flag(ghcjs_windows)`

- Go ahead and try to use `unix` package in windows (as suggested by @luite in https://github.com/ghcjs/ghcjs/issues/487#issuecomment-229775802)
 
The preferred one would be the second one, my first attempt replacing
```
- IfUnix:    ./pkg/unix
- IfWindows: ./pkg/Win32
```
with
```
- ./pkg/unix
```
throws:
```console
....
checking for dlfcn.h... no
....
In file included from Resource.hsc:28:0:
include/HsUnix.h:86:10: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
          ^~~~~~~~~
compilation terminated.
compiling dist\build\System\Posix\Resource_hsc_make.c failed (exit code 1)
```

But i am afraid i am not sure if my c and c toolchain (configure, make, etc) knowledge will be enough to acomplish it. It would be possible to get some help to continue that path?

Related issues:
- https://github.com/ghcjs/ghcjs/issues/487
- https://github.com/ghcjs/ghcjs/issues/548
- https://github.com/ghcjs/ghcjs/issues/559
- https://github.com/ghcjs/ghcjs/issues/596

### CODE REVIEW

**Comment by jneira** [comment]
NOTE, Due to the weird cpp combinations to build `base` i had to unpack `boot.tar` and modify
`./pkg/base/System/Environment/Blank.hsc`.
The cpp conditionals introduced by ghcjs but being built them in windows reach a [code path](https://github.com/ghc/ghc/blob/master/libraries/base/System/Environment/Blank.hsc#L185) that doesnt compile (so is a ghc bug i think):

So i had to replace:
```haskell
putEnv :: String -> IO ()
putEnv keyvalue = do
  s <- getFileSystemEncoding >>= (`newCString` keyvalue)
  -- IMPORTANT: Do not free `s` after calling putenv!
  --
  -- According to SUSv2, the string passed to putenv becomes part of the
  -- environment. #7342
  throwErrnoIf_ (/= 0) "putenv" (c_putenv s)
```
with
```haskell
putEnv :: String -> IO ()
putEnv keyvalue = do
  s <- newCString keyvalue
  -- IMPORTANT: Do not free `s` after calling putenv!
  --
  -- According to SUSv2, the string passed to putenv becomes part of the
  -- environment. #7342
  throwErrnoIf_ (/= 0) "putenv" (c_putenv s)
```

**Comment by NickSeagull** [comment]
Let me know if I can help with anything!

**Comment by jneira** [comment]
Travis is begging about checking out transformers, the commit seems to be unreachable with a direct `git submodule update --recursive`. I had to do a `git submodule sync` to update the submodule.

**Comment by jneira** [comment]
For now i am trying to build the unix package, the progress so far is in this repo: https://github.com/jneira/ghcjs-unix
Basically [i am adding all c "constants" from posix missing in windows](https://github.com/jneira/ghcjs-unix/blob/master/include/HsUnix.h#L122) needed by `hsc2hs-ghcjs` to compile .hsc files.

**Comment by jneira** [comment]
Ok, i've got to tweak HsUnix.h header file to make unix build in windows. Not sure how is going to work at runtime, though.
After unix, the rest of packages included Cabal were built succesfully.
I' ve tried to build a simple cabal project and it works with `cabal new-build --ghcjs && node dist-newstyle\build\x86_64-linux\ghcjs-8.6.0.1\cabal-test-0.1.0.0\x\cabal-test\build\cabal-test\cabal-test.jsexe\all.js`
Note that cabal is creating the build files under `x86_64-linux`.
I am afraid that `cabal install` doesn't work out-of-the.box: i had to include the user package db explicitly although `ghcjs-pkg` is aware of its location. Log with `--ghcjs-option=-v3` only shows:

```console
> cabal install --ghcjs --ghcjs-options="-v3"

Glasgow Haskell Compiler for JavaScript, Version 8.6.5, stage 2 booted by GHC version 8.6.1
Using binary package database: D:\bin\ghcjs\x86_64-mingw32-8.6.0.1-8.6.5\lib\package.conf.d\package.cache
Using binary package database: dist\package.conf.inplace\package.cache
package flags [-package-id base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q{unit base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q True ([])},
               -package-id bytestring-0.10.8.2-FBklFuapa1a7kq4yflY7Bt{unit bytestring-0.10.8.2-FBklFuapa1a7kq4yflY7Bt True ([])},
               -package-id http-types-0.12.3-8pLfKlD5DWRCPJfiUmYRpE{unit http-types-0.12.3-8pLfKlD5DWRCPJfiUmYRpE True ([])}]
loading package database D:\bin\ghcjs\x86_64-mingw32-8.6.0.1-8.6.5\lib\package.conf.d
loading package database dist\package.conf.inplace
<command line>: cannot satisfy -package-id http-types-0.12.3-8pLfKlD5DWRCPJfiUmYRpE

> ghcjs-pkg --user list

C:\Users\user\AppData\Roaming\ghcjs\x86_64-mingw32-8.6.0.1-8.6.5\package.conf.d
    cabal-test-0.1.0.0
    case-insensitive-1.2.1.0
    hashable-1.2.7.0
    http-types-0.12.3
```

If i add manually my user db in in options, it works:

```console
> cabal install --ghcjs --ghcjs-options="-package-db C:\Users\user\AppData\Roaming\ghcjs\x86_64-mingw32-8.6.0.1-8.6.5\package.conf.d -v3"
.....
Resolving dependencies...
In order, the following will be installed:
cabal-test-0.1.0.0 (reinstall)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Starting     cabal-test-0.1.0.0
Building     cabal-test-0.1.0.0
Completed    cabal-test-0.1.0.0

> node D:\path\to\global\bin\cabal-test.jsexe\all.js

Hello, Haskell!
%2FC:%2Fsd%20%28eta%29
```

**Comment by jneira** [comment]
All right, it seems the project can be built in windows without manual changes:
- Using mingw64 console and running in the ghcjs sources project folder
- `pacman -Sy git tar binutils autoconf make libtool automake python3 p7zip patch gcc`
-  `cd ghc && ./mk/get-win32-tarballs.sh download x86_64 && cd..` 
- `./utils/makePackages.sh`
- `./utils/makeSandbox.sh && cabal install` or `cabal new-build` or `stack install` (i've tested the three methods)
- You have take in account that `ghcjs-boot` will copy the mingw installed with ghc in the parent folder where `ghcjs.exe` is placed so i copied the executables in a install layout similar to ghc:
```
ghcjs
├───x86_64-mingw32-8.6.0.1-8.6.5
    ├───bin (executables)
    ├───lib (folder where ghcjs-boot will copy boot packages and other files) 
    ├───mingw
```
So you will have to 
* Edit `ghcjs-{version}.exe.options` and `haddock-ghcjs-{version}.exe.options` adding `-BX:\path\to\ghcjs\x86_64-mingw32-8.6.0.1-8.6.5\lib`
* Edit `ghcjs-pkg-{version}.exe.options`to add `--global-package-db X:\path\to\ghcjs\x86_64-mingw32-8.6.0.1-8.6.5\lib\package.conf.d` and `--user-package-db C:\Users\user\AppData\Roaming\ghcjs\x86_64-mingw32-8.6.0.1-8.6.5\package.conf.d`

And finally run (in mingw console): `ghcjs-boot -S /path/to/ghcjs-source/data/boot.tar`

I will appreciate if you give a try, i've tested it in a windows 7 and a windows 10. I've not tried it i na linux env to check i it doesnt break anything!

**Comment by jneira** [comment]
@luite sorry for ping again but do you think this could be merged after the proper tests, reviews and changes? There is a great and hard job already done to support windows and it would be great being able to benefit from it.

**Comment by jneira** [comment]
* To test `ghcjs` executables i am trying to compile the dhall lang haskell binding: https://github.com/dhall-lang/dhall-haskell/tree/master/dhall
* I'm going to need patch several packages to make it compile with ghcjs in windows. I am going to save the patches in this repo: https://github.com/jneira/ghcjs-hackage/tree/master/patches
* The problem is `ghcjs` and `cabal --ghcjs` don't know about being compiled in windows but gcc shipped with ghc mingw bundle has the headers related with os/arch:
```c
// # gcc -dM -E - < /dev/null
#define _WIN32 1
#define _WIN64 1
#define __x86_64 1
#define __GNUC_PATCHLEVEL__ 0
#define __WIN32 1
#define __WIN64 1
#define __MINGW32__ 1
#define __GNUC__ 7
#define __WINNT 1
#define __WINNT__ 1
#define __WIN32__ 1
#define __amd64 1
#define __x86_64__ 1
#define __amd64__ 1
#define WIN32 1
#define WIN64 1
#define __MINGW64__ 1
#define __WIN64__ 1
```
So gcc/ghc thinks it is under `WINXX, MINGWXX, etc`, but we want to compile under unix/linux code paths :worried:

**Comment by hvr** [comment]
> The problem is ghcjs and cabal --ghcjs don't know about being compiled in windows

can you elaborate on that one? It's been a pet peeve of mine for some time that `ghcjs --info` lies about the target architecture, i.e.

```
$ ghcjs --info | grep -Fi target
 ,("target os","OSLinux")
 ,("target arch","ArchX86_64")
 ,("target word size","8")
 ,("target has GNU nonexec stack","True")
 ,("target has .ident directive","True")
 ,("target has subsections via symbols","False")
 ,("target has RTS linker","YES")
 ,("Target platform","x86_64-unknown-linux")
```

which is plain wrong, as ghcjs obviously doesn't produce binaries for `x86_64-unknown-linux` and every tool which believes ghcjs' lie risks running into issues. Is this something your patch series address? Does this even relate to your issue at all? And what business does `ghcjs` with calling `gcc` anyway (except maybe for the sake of `-XCPP`?)

**Comment by jneira** [comment]
My info is similar:
```console
# ghcjs --info | grep -Fi target
 ,("target os","OSMinGW32")
 ,("target arch","ArchX86_64")
 ,("target word size","8")
 ,("target has GNU nonexec stack","False")
 ,("target has .ident directive","True")
 ,("target has subsections via symbols","False")
 ,("target has RTS linker","YES")
 ,("Target platform","x86_64-unknown-linux")
```
and cpp relevant defs(with `touch foo.hs && ghcjs -E -optP-dM -cpp foo.hspp`):

```
#define ghcjs_HOST_OS 1
#define __GHCJS__ 806
#define x86_64_BUILD_ARCH 1
#define mingw32_BUILD_OS 1
#define ghcjs_HOST_ARCH 1
```
(`mingw32_HOST_OS` not present)

With those values `cabal --ghcjs` condition `os(windows)` is false so it tries to build packages with the default os (usually *nix). But in c header files (and haskell ones) `_WIN32`  is defined so the mix usually doesnt match.

The big problem is with `hsc2hs` cause it tries to load headers non existent in `mingw` (at least in the `mingw` bundled with ghc). Also, as you noted, most cpp definitions (in `.hsc` or `.hs`) are not there.

So i am trying to hack around the problem creating the missing cpp definitions and avoid the headers, f.e. for `basement` (Basement/Terminal/Size.hsc):

```haskell
# if defined(__GHCJS__) && defined(_WIN32)
#  include <ghcjswin.h>
# else
#  include <sys/ioctl.h>
# endif
```

being in `ghcjswin.h` the missing c/cpp defs used in `Size.hsc`

```c
// from termios.h
struct winsize
{
  unsigned short ws_row, ws_col;
  unsigned short ws_xpixel, ws_ypixel;
};

#define TIOCGWINSZ (('T' << 8) | 1)
#define TIOCSWINSZ (('T' << 8) | 2)
#define TIOCLINUX  (('T' << 8) | 3)
#define TIOCGPGRP  (('T' << 8) | 0xf)
#define TIOCSPGRP  (('T' << 8) | 0x10)
```

Definitely an ugly hack, but i didnt find a better way to do it :-/

**Comment by jneira** [comment]
In my tests the cabal condition `os(ghcjs)` doesnt hold either and i have to use `impl(ghcjs)`.
So as you suggested, maybe the target platform should be something like `x86_64-ghcjs` and the condition `os(ghcjs)` should work?. 
Maybe the reason of this is patches becomes easier when the build os is unix (??).

**Comment by jneira** [comment]
In the bright side i've got to build `dhall` with `cabal install -f-with-http` after patching some of its dependent packages:
```console
D:\bin>echo let a = 1 in a + 2 | node dhall.jsexe\all.js
3
```

**Pull request closed without merging**
