### PR TITLE
Merge ghc-8.0 to master

### LINKED ISSUE #526: Either making "ghc-8.0" the new master, or making it the GitHub default branch
Since `ghc-8.0` is the current bleeding edge of development, I think it makes sense to have it bet the GitHub default branch.  This means that:

* It will be the branch visible when you visit the repo

* It will be the default destination for PRs

I think this will be clearer to contributors!

### PR DESCRIPTION
**Pull request by spl**
I'm rather concerned about doing a force-push to `master`, so I did a normal merge. This branch is now [identical](https://github.com/ghcjs/ghcjs/compare/ghc-8.0...spl:merged-ghc-8.0-to-master) to `ghc-8.0` but can be merged to `master` without conflicts.

I think it would be a good idea to create a `ghc-7.10` branch from `master`, as @mgsloan suggested on #526, before merging this.

Resolves #526

### CODE REVIEW

**Comment by Ericson2314** [comment]
While we did merge before for improved-base I'm not really a fan because ghc-8.0 isn't ready to subsume ghc-7.0 for all purposes---and IMO the merge implies that it is ready.

**Comment by spl** [comment]
@Ericson2314:

> While we did merge before for improved-base I'm not really a fan because ghc-8.0 isn't ready to subsume ghc-7.0 for all purposes---and IMO the merge implies that it is ready.

(I don't necessarily agree or disagree with you. Just trying to help figure out the situation.)

I guess the questions are: where is future development going to occur and where should PRs be targeted? Without extra information, people will target PRs at the default GitHub branch. Currently, `ghc-8.0` has diverged quite far from `master`, and if the development continues there, it will continue to diverge, and new PRs will be more difficult to merge into that branch.

Alternatively stated, is there any reason to keep `master` around, in its current state, as the default branch? That is, is there going to be ongoing feature development on it, or could it be seen as a bug-fix/release branch?

**Comment by Ericson2314** [comment]
@spl Sorry should have mentioned I came here from the issue. I was advocating the forced push route, not leave master as is. My point is roughly that `ghc-8` should have been `master`, and `master` `stable` to begin with, and with a forced push we can pretend that it was. Since we're not actually erasing history, I feel less squeamish about the forced push route.

**Comment by spl** [comment]
@Ericson2314: Sorry, I'm a bit confused. Are you advocating a force-push over the merge in this PR? What is the advantage of a force-push? Even if the server history is not being rewritten or lost, couldn't a force-push create problems for people who have clones or local copies of `master` with additional commits?

**Comment by Ericson2314** [comment]
@spl the problem is the merge itself to me signifies that the one branch has been subsumed into the other, when that's not quite the case. Maybe it's best is to just delete master for a while, keeping `ghc-8.0` and `ghc-7.10`, and then reintroduce it later rather than immediately force-pushing.

**Comment by spl** [comment]
Okay. I would favor merging, but I don't have a strong opinion about it.

**Comment by sunjay** [comment]
Can you at least add a note in the installation instructions for people using ghc 8? I didn't realize this branch existed until I accidentally stumbled upon this pull request.

For GHC 8, you need to clone this repo, checkout the ghc-8.0 branch, then run `cabal install ./ghcjs` from the parent directory to the one you cloned the repo into.

```
git clone https://github.com/ghcjs/ghcjs
cd ghcjs
git checkout ghc-8.0
cd ..
cabal install ./ghcjs
```

Works perfectly once you're on this branch.

**Comment by tolysz** [comment]
I would have a strong opinion if the `ghcjs --interactive` was working with the 8 branch. The opinion would be to find who is still using 7.10 versions and ask someone from those folks to volunteer to be this branch manager, and all other efforts should go for 8+.
It is so much easier for me to build images for `stack` for `ghcjs8` than the older ones, and if there were no uses(eg. interactive) for it I would just drop it.

**Comment by mgsloan** [comment]
I'm highly in favor of doing a merge, because then PRs will target the right branch.  We can take the `master` branch before this merge and make it a `ghc-7.10` branch.

I'm actually rather impressed this merge was feasible, It thought the branches had diverged too much.  Good stuff @spl!

**Comment by hamishmack** [comment]
Is this blocked by #549?

**Pull request closed without merging**
